#!/usr/bin/env python3
"""Functional smoke test for the LGPL-only PyAV build.

Run inside the test environment that has the built wheel, numpy and pillow installed::

    build/lgpl-media/testenv/bin/python packaging/ffmpeg/smoke_lgpl_media.py \
        [--ffmpeg /opt/homebrew/bin/ffmpeg] [--work-dir DIR] [--report report.json]

Required checks (exit status 1 if any fails): royalty-free encode/decode round trips,
absent patent-encumbered codecs, a bwdif filter graph and the audio resampler.

Exploratory checks (reported, never fatal): stream-copy of AAC (and H.264) from
fixtures generated by a user-installed ``ffmpeg`` binary -- used only to create test
inputs, never linked -- and how PyAV exposes streams whose decoder is absent.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import traceback
from fractions import Fraction
from pathlib import Path

import av
import numpy as np

WIDTH, HEIGHT, FRAMES, RATE = 320, 240, 30, 30
AUDIO_RATE = 48000

RESULTS: list[dict] = []


def record(name: str, required: bool = True):
    """Decorator: run a check, record pass/fail with details or the exception."""

    def wrap(function):
        def run(*args, **kwargs):
            entry = {"name": name, "required": required}
            try:
                details = function(*args, **kwargs)
                entry.update(passed=True, details=details)
            except Exception as exc:  # noqa: BLE001 - every failure must be reported
                entry.update(
                    passed=False,
                    error=f"{type(exc).__name__}: {exc}",
                    traceback=traceback.format_exc(limit=4),
                )
            RESULTS.append(entry)
            status = "PASS" if entry["passed"] else ("FAIL" if required else "INFO-FAIL")
            print(f"[{status}] {name}", flush=True)
            if not entry["passed"]:
                print(f"    {entry['error']}", flush=True)
            return entry

        return run

    return wrap


def rgb_frame(index: int) -> np.ndarray:
    y, x = np.mgrid[0:HEIGHT, 0:WIDTH]
    image = np.empty((HEIGHT, WIDTH, 3), dtype=np.uint8)
    image[..., 0] = (x + index * 8) % 256
    image[..., 1] = (y + index * 4) % 256
    image[..., 2] = ((x + y) // 2 + index * 16) % 256
    return image


def audio_chunk(start: int, samples: int) -> np.ndarray:
    t = (np.arange(start, start + samples) / AUDIO_RATE).astype(np.float64)
    left = 0.3 * np.sin(2 * np.pi * 440 * t)
    right = 0.3 * np.sin(2 * np.pi * 660 * t)
    interleaved = np.empty(2 * samples, dtype=np.int16)
    interleaved[0::2] = (left * 32767).astype(np.int16)
    interleaved[1::2] = (right * 32767).astype(np.int16)
    return interleaved.reshape(1, -1)


def encode(
    path: Path,
    container_format: str,
    codec: str,
    pix_fmt: str,
    options: dict[str, str] | None = None,
    color: dict[str, int] | None = None,
    with_opus: bool = False,
) -> dict:
    with av.open(str(path), "w", format=container_format) as output:
        video = output.add_stream(codec, rate=RATE, options=options or {})
        video.width, video.height, video.pix_fmt = WIDTH, HEIGHT, pix_fmt
        video.time_base = Fraction(1, RATE)
        if color:
            for key, value in color.items():
                setattr(video.codec_context, key, value)
        audio = None
        if with_opus:
            audio = output.add_stream("libopus", rate=AUDIO_RATE, layout="stereo")
            audio.format = "s16"
        for index in range(FRAMES):
            frame = av.VideoFrame.from_ndarray(rgb_frame(index), format="rgb24")
            if color:
                frame = frame.reformat(
                    format=pix_fmt, dst_colorspace=av.video.reformatter.Colorspace.BT2020
                )
                for key, value in color.items():
                    setattr(frame, key, value)
            frame.pts = index
            frame.time_base = Fraction(1, RATE)
            for packet in video.encode(frame):
                output.mux(packet)
        for packet in video.encode(None):
            output.mux(packet)
        if audio is not None:
            # One second of audio in 1024-sample chunks (PyAV re-chunks to 960 for Opus).
            position = 0
            while position < AUDIO_RATE:
                frame = av.AudioFrame.from_ndarray(
                    audio_chunk(position, 1024), format="s16", layout="stereo"
                )
                frame.sample_rate = AUDIO_RATE
                frame.pts = position
                frame.time_base = Fraction(1, AUDIO_RATE)
                position += 1024
                for packet in audio.encode(frame):
                    output.mux(packet)
            for packet in audio.encode(None):
                output.mux(packet)
    return {"bytes": path.stat().st_size}


def decode_check(path: Path, expect_codec: str, pix_fmt: str | None = None) -> dict:
    with av.open(str(path)) as container:
        stream = container.streams.video[0]
        codec_name = stream.codec_context.name
        frames = 0
        last_pts = None
        formats = set()
        color = None
        for frame in container.decode(video=0):
            if frame.width != WIDTH or frame.height != HEIGHT:
                raise AssertionError(f"frame {frames} is {frame.width}x{frame.height}")
            if frame.pts is None or (last_pts is not None and frame.pts <= last_pts):
                raise AssertionError(f"pts not increasing: {last_pts} -> {frame.pts}")
            last_pts = frame.pts
            formats.add(frame.format.name)
            color = {
                "color_primaries": int(frame.color_primaries),
                "color_trc": int(frame.color_trc),
                "colorspace": int(frame.colorspace),
                "color_range": int(frame.color_range),
            }
            frames += 1
        audio_info = None
        if container.streams.audio:
            container.seek(0)
            samples = 0
            last = None
            for frame in container.decode(audio=0):
                if last is not None and frame.pts <= last:
                    raise AssertionError(f"audio pts not increasing: {last} -> {frame.pts}")
                last = frame.pts
                samples += frame.samples
            audio_stream = container.streams.audio[0]
            audio_info = {
                "codec": audio_stream.codec_context.name,
                "rate": audio_stream.codec_context.sample_rate,
                "channels": audio_stream.codec_context.channels,
                "decoded_samples": samples,
            }
            if audio_info["rate"] != AUDIO_RATE or audio_info["channels"] != 2 or samples < 40000:
                raise AssertionError(f"unexpected audio decode result {audio_info}")
    if codec_name != expect_codec:
        raise AssertionError(f"decoder {codec_name!r}, expected {expect_codec!r}")
    if frames != FRAMES:
        raise AssertionError(f"decoded {frames} frames, expected {FRAMES}")
    if pix_fmt and formats != {pix_fmt}:
        raise AssertionError(f"decoded formats {formats}, expected {pix_fmt}")
    return {
        "decoder": codec_name,
        "stream_codec_expected": expect_codec,
        "frames": frames,
        "formats": sorted(formats),
        "last_color": color,
        "audio": audio_info,
    }


def round_trip(work: Path, name: str, **kwargs) -> dict:
    path = work / name
    expect = kwargs.pop("expect")
    decode_fmt = kwargs.pop("decode_fmt", None)
    encoded = encode(path, **kwargs)
    return {"file": path.name, **encoded, **decode_check(path, expect, decode_fmt)}


def stream_description(stream) -> dict:
    """Everything PyAV exposes about a stream, tolerating absent decoders."""
    info: dict[str, object] = {
        "repr": repr(stream),
        "class": type(stream).__name__,
        "type": stream.type,
        "index": stream.index,
        "codec_context_is_none": stream.codec_context is None,
        "time_base": str(stream.time_base),
        "duration": stream.duration,
        "frames": stream.frames,
        "metadata": dict(stream.metadata),
    }
    for attribute in ("name", "codec", "codec_tag", "profile", "width", "height", "sample_rate"):
        try:
            value = getattr(stream, attribute)
            info[attribute] = value if isinstance(value, (str, int, type(None))) else repr(value)
        except Exception as exc:  # noqa: BLE001
            info[attribute] = f"raises {type(exc).__name__}: {exc}"
    if stream.codec_context is not None:
        info["codec_context_name"] = stream.codec_context.name
    return info


@record("AV1 (libsvtav1 yuv420p crf35 preset8) in MP4")
def check_av1_mp4(work: Path):
    return round_trip(
        work,
        "av1.mp4",
        container_format="mp4",
        codec="libsvtav1",
        pix_fmt="yuv420p",
        options={"crf": "35", "preset": "8"},
        expect="libdav1d",
        decode_fmt="yuv420p",
    )


@record("AV1 (libsvtav1 yuv420p crf35 preset8) in MKV")
def check_av1_mkv(work: Path):
    return round_trip(
        work,
        "av1.mkv",
        container_format="matroska",
        codec="libsvtav1",
        pix_fmt="yuv420p",
        options={"crf": "35", "preset": "8"},
        expect="libdav1d",
        decode_fmt="yuv420p",
    )


@record("VP9 (libvpx-vp9) in WebM")
def check_vp9_webm(work: Path):
    return round_trip(
        work,
        "vp9.webm",
        container_format="webm",
        codec="libvpx-vp9",
        pix_fmt="yuv420p",
        options={"crf": "35", "b": "0", "deadline": "realtime", "cpu-used": "8"},
        expect="vp9",
        decode_fmt="yuv420p",
    )


@record("VP9 (libvpx-vp9) in MP4")
def check_vp9_mp4(work: Path):
    return round_trip(
        work,
        "vp9.mp4",
        container_format="mp4",
        codec="libvpx-vp9",
        pix_fmt="yuv420p",
        options={"crf": "35", "b": "0", "deadline": "realtime", "cpu-used": "8"},
        expect="vp9",
        decode_fmt="yuv420p",
    )


@record("FFV1 in MKV")
def check_ffv1_mkv(work: Path):
    return round_trip(
        work,
        "ffv1.mkv",
        container_format="matroska",
        codec="ffv1",
        pix_fmt="yuv420p",
        expect="ffv1",
        decode_fmt="yuv420p",
    )


@record("10-bit AV1 (yuv420p10le) with BT.2020/HLG tags in MKV")
def check_av1_10bit(work: Path):
    from av.video.reformatter import ColorPrimaries, ColorRange, ColorTrc

    color = {
        "color_primaries": int(ColorPrimaries.BT2020),
        "color_trc": int(ColorTrc.ARIB_STD_B67),
        "colorspace": 9,  # AVCOL_SPC_BT2020_NCL
        "color_range": int(ColorRange.MPEG),
    }
    result = round_trip(
        work,
        "av1-10bit-hlg.mkv",
        container_format="matroska",
        codec="libsvtav1",
        pix_fmt="yuv420p10le",
        options={"crf": "35", "preset": "8"},
        color=color,
        expect="libdav1d",
        decode_fmt="yuv420p10le",
    )
    with av.open(str(work / "av1-10bit-hlg.mkv")) as container:
        context = container.streams.video[0].codec_context
        stream_color = {
            "color_primaries": int(context.color_primaries),
            "color_trc": int(context.color_trc),
            "colorspace": int(context.colorspace),
            "color_range": int(context.color_range),
        }
    if result["last_color"] != color:
        raise AssertionError(f"decoded frame color tags {result['last_color']} != {color}")
    result["stream_color"] = stream_color
    return result


@record("Opus (48 kHz stereo) + AV1 in MP4")
def check_opus_av1_mp4(work: Path):
    return round_trip(
        work,
        "av1-opus.mp4",
        container_format="mp4",
        codec="libsvtav1",
        pix_fmt="yuv420p",
        options={"crf": "35", "preset": "8"},
        with_opus=True,
        expect="libdav1d",
        decode_fmt="yuv420p",
    )


@record("patent-encumbered codecs are absent")
def check_absent_codecs():
    outcomes = {}
    for name, mode in (
        ("libx264", "w"),
        ("h264", "r"),
        ("aac", "w"),
        ("aac", "r"),
        ("hevc", "r"),
    ):
        try:
            av.codec.Codec(name, mode)
        except Exception as exc:  # noqa: BLE001
            outcomes[f"{name}/{mode}"] = f"raises {type(exc).__name__}: {exc}"
        else:
            outcomes[f"{name}/{mode}"] = "AVAILABLE"
    present = [key for key, value in outcomes.items() if value == "AVAILABLE"]
    if present:
        raise AssertionError(f"codecs unexpectedly available: {present}")
    return outcomes


@record("bwdif filter graph")
def check_bwdif():
    graph = av.filter.Graph()
    source = graph.add_buffer(
        width=WIDTH, height=HEIGHT, format="yuv420p", time_base=Fraction(1, RATE)
    )
    bwdif = graph.add("bwdif", "mode=send_field:parity=tff:deint=all")
    sink = graph.add("buffersink")
    source.link_to(bwdif)
    bwdif.link_to(sink)
    graph.configure()
    produced = []
    for index in range(6):
        frame = av.VideoFrame.from_ndarray(rgb_frame(index), format="rgb24").reformat(
            format="yuv420p"
        )
        frame.pts = index
        frame.time_base = Fraction(1, RATE)
        graph.push(frame)
        while True:
            try:
                produced.append(graph.pull())
            except (av.BlockingIOError, av.EOFError):
                break
    graph.push(None)
    while True:
        try:
            produced.append(graph.pull())
        except (av.BlockingIOError, av.EOFError):
            break
    if len(produced) < 6:
        raise AssertionError(f"bwdif send_field produced only {len(produced)} frames")
    return {
        "input_frames": 6,
        "output_frames": len(produced),
        "size": [produced[0].width, produced[0].height],
    }


@record("AudioResampler")
def check_resampler():
    resampler = av.AudioResampler(format="fltp", layout="mono", rate=16000)
    frame = av.AudioFrame.from_ndarray(audio_chunk(0, 4800), format="s16", layout="stereo")
    frame.sample_rate = AUDIO_RATE
    frame.pts = 0
    frame.time_base = Fraction(1, AUDIO_RATE)
    out = resampler.resample(frame) + resampler.resample(None)
    samples = sum(item.samples for item in out)
    if not 1500 <= samples <= 1700:
        raise AssertionError(f"resampled {samples} samples, expected about 1600")
    return {
        "frames": len(out),
        "samples": samples,
        "format": out[0].format.name,
        "layout": out[0].layout.name,
        "rate": out[0].sample_rate,
    }


def make_fixtures(ffmpeg: str, work: Path) -> dict[str, Path]:
    fixtures = {
        "aac_only.mp4": [
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=48000:duration=2",
            "-c:a",
            "aac",
            "-b:a",
            "128k",
        ],
        "h264_aac.mp4": [
            "-f",
            "lavfi",
            "-i",
            f"testsrc2=size={WIDTH}x{HEIGHT}:rate={RATE}:duration=1",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=48000:duration=1",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-shortest",
        ],
        "hevc_aac.mkv": [
            "-f",
            "lavfi",
            "-i",
            f"testsrc2=size={WIDTH}x{HEIGHT}:rate={RATE}:duration=1",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=48000:duration=1",
            "-c:v",
            "libx265",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-shortest",
        ],
    }
    made = {}
    for name, arguments in fixtures.items():
        target = work / name
        result = subprocess.run(
            [ffmpeg, "-hide_banner", "-loglevel", "error", "-y", *arguments, str(target)],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            made[name] = target
        else:
            print(f"    fixture {name} not generated: {result.stderr.strip()[-300:]}")
    return made


def remux(
    source: Path,
    target: Path,
    container_format: str,
    stream_types: set[str],
    opaque: bool | None = None,
) -> dict:
    with av.open(str(source)) as input_container:
        with av.open(str(target), "w", format=container_format) as output:
            mapping = {}
            for stream in input_container.streams:
                if stream.type in stream_types:
                    mapping[stream.index] = output.add_stream_from_template(stream, opaque=opaque)
            packets = 0
            for packet in input_container.demux(*[input_container.streams[i] for i in mapping]):
                if packet.dts is None:
                    continue  # demuxer flush packet
                packet.stream = mapping[packet.stream.index]
                output.mux(packet)
                packets += 1
    with av.open(str(target)) as check:
        streams = [stream_description(stream) for stream in check.streams]
        read_back = sum(1 for packet in check.demux() if packet.dts is not None)
    if packets == 0 or read_back != packets:
        raise AssertionError(f"muxed {packets} packets but read back {read_back}")
    return {
        "target": target.name,
        "muxed_packets": packets,
        "read_back_packets": read_back,
        "bytes": target.stat().st_size,
        "output_streams": streams,
    }


def mux_stream_copy(ffmpeg: str, source: Path, target: Path, container_format: str) -> dict:
    """Copy the AAC track with ``add_mux_stream('aac')`` (no codec context).

    PyAV cannot name the codec of a decoder-less stream, so the caller must already know
    it is AAC. The result is validated with the user's ffprobe/ffmpeg (fixture tools).
    """
    with av.open(str(source)) as input_container:
        with av.open(str(target), "w", format=container_format) as output:
            template = input_container.streams.audio[0]
            stream = output.add_mux_stream("aac", rate=AUDIO_RATE)
            stream.time_base = template.time_base
            packets = 0
            for packet in input_container.demux(template):
                if packet.dts is None:
                    continue
                packet.stream = stream
                output.mux(packet)
                packets += 1
    ffprobe = str(Path(ffmpeg).with_name("ffprobe"))
    probe = subprocess.run(
        [ffprobe, "-v", "error", "-show_entries", "stream=codec_name,channels,extradata_size"]
        + ["-of", "compact", str(target)],
        capture_output=True,
        text=True,
    )
    decode = subprocess.run(
        [ffmpeg, "-v", "error", "-i", str(target), "-f", "null", "-"],
        capture_output=True,
        text=True,
    )
    details = {
        "muxed_packets": packets,
        "ffprobe": (probe.stdout + probe.stderr).strip()[-400:],
        "ffmpeg_decode_errors": decode.stderr.strip()[-400:],
    }
    if decode.returncode != 0 or decode.stderr.strip():
        raise AssertionError(f"copied AAC track is not decodable by ffmpeg: {details}")
    return details


def exploratory_checks(ffmpeg: str | None, work: Path) -> None:
    if (work / "av1-opus.mp4").exists():
        for opaque in (None, True):

            @record(
                "control: stream copy AV1+Opus (decoders present) mp4 -> matroska "
                f"(add_stream_from_template, opaque={opaque})",
                required=False,
            )
            def control(opaque=opaque):
                return remux(
                    work / "av1-opus.mp4",
                    work / f"copy-av1-opus-opaque-{opaque}.mkv",
                    "matroska",
                    {"audio", "video"},
                    opaque=opaque,
                )

            control()
    if not ffmpeg:
        RESULTS.append(
            {
                "name": "AAC stream copy",
                "required": False,
                "passed": False,
                "error": "skipped: no ffmpeg binary available to generate AAC fixtures",
            }
        )
        return
    fixtures = make_fixtures(ffmpeg, work)

    @record("inspect absent-decoder streams (AAC/H.264/HEVC inputs)", required=False)
    def inspect():
        report = {}
        for name, path in fixtures.items():
            with av.open(str(path)) as container:
                entry = {
                    "container_format": container.format.name,
                    "streams": [stream_description(s) for s in container.streams],
                }
                decode_attempts = {}
                for stream in container.streams:
                    try:
                        next(iter(container.decode(stream)), None)
                        decode_attempts[f"#{stream.index}"] = "decode OK"
                    except Exception as exc:  # noqa: BLE001
                        decode_attempts[f"#{stream.index}"] = (
                            f"raises {type(exc).__module__}.{type(exc).__name__}: {exc}"
                        )
                    container.seek(0)
                entry["decode_attempts"] = decode_attempts
                report[name] = entry
        return report

    inspect()
    for source_name, types, formats in (
        ("aac_only.mp4", {"audio"}, ("mp4", "matroska")),
        ("h264_aac.mp4", {"audio"}, ("mp4", "matroska")),
        ("h264_aac.mp4", {"audio", "video"}, ("mp4", "matroska")),
        ("hevc_aac.mkv", {"audio", "video"}, ("mp4", "matroska")),
    ):
        if source_name not in fixtures:
            continue
        for container_format in formats:
            suffix = "mp4" if container_format == "mp4" else "mkv"
            label = "+".join(sorted(types))
            target = work / f"copy-{Path(source_name).stem}-{label}.{suffix}"

            @record(
                f"stream copy {label} from {source_name} -> {container_format} "
                "(add_stream_from_template)",
                required=False,
            )
            def copy(source=fixtures[source_name], target=target, fmt=container_format, t=types):
                return remux(source, target, fmt, t)

            copy()
    if "aac_only.mp4" in fixtures:
        for container_format in ("mp4", "matroska"):
            suffix = "mp4" if container_format == "mp4" else "mkv"
            target = work / f"muxcopy-aac.{suffix}"

            @record(
                f"stream copy audio from aac_only.mp4 -> {container_format} "
                "(add_mux_stream('aac'), no codec context)",
                required=False,
            )
            def mux_copy(target=target, fmt=container_format):
                return mux_stream_copy(ffmpeg, fixtures["aac_only.mp4"], target, fmt)

            mux_copy()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--ffmpeg", default=shutil.which("ffmpeg"), help="Fixture generator")
    parser.add_argument("--work-dir", type=Path, help="Keep outputs here (default: temp dir)")
    parser.add_argument("--report", type=Path, help="Write the JSON report here")
    args = parser.parse_args()
    temporary = None
    if args.work_dir:
        work = args.work_dir.resolve()
        work.mkdir(parents=True, exist_ok=True)
    else:
        temporary = tempfile.TemporaryDirectory(prefix="lgpl-media-smoke-")
        work = Path(temporary.name)
    print(f"PyAV {av.__version__} from {av.__file__}")
    print(f"FFmpeg {av.ffmpeg_version_info}; libavcodec {av.library_versions['libavcodec']}")
    try:
        check_av1_mp4(work)
        check_av1_mkv(work)
        check_vp9_webm(work)
        check_vp9_mp4(work)
        check_ffv1_mkv(work)
        check_av1_10bit(work)
        check_opus_av1_mp4(work)
        check_absent_codecs()
        check_bwdif()
        check_resampler()
        exploratory_checks(args.ffmpeg, work)
    finally:
        report = {
            "av_version": av.__version__,
            "ffmpeg_version": av.ffmpeg_version_info,
            "fixture_ffmpeg": args.ffmpeg,
            "results": RESULTS,
            "required_passed": all(r["passed"] for r in RESULTS if r["required"]),
        }
        text = json.dumps(report, indent=2, default=str)
        if args.report:
            args.report.write_text(text + "\n")
        if temporary is not None:
            temporary.cleanup()
    print(text)
    return 0 if report["required_passed"] else 1


if __name__ == "__main__":
    sys.exit(main())
