#!/usr/bin/env python3
"""Refresh reviewed backend locks with uv; release builds never run this resolver."""

from __future__ import annotations

import argparse
import subprocess

from release_targets import ROOT, targets


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", choices=[target["id"] for target in targets()])
    args = parser.parse_args()
    resolver = subprocess.check_output(["uv", "--version"], text=True).strip()
    for target in targets():
        if args.target and target["id"] != args.target:
            continue
        if target["platform"] == "macos":
            continue  # macOS builds natively and has no cross-resolved lock.
        lock = ROOT / "requirements/locks" / f"{target['id']}.txt"
        source = "backend-directml.in" if target["backend"] == "DirectML" else "backend-modern.in"
        backend = "cpu" if target["backend"] == "DirectML" else target["index"]
        platform = (
            "x86_64-pc-windows-msvc" if target["platform"] == "windows" else "x86_64-manylinux_2_28"
        )
        print(f"Resolving {target['id']}", flush=True)
        subprocess.run(
            [
                "uv",
                "pip",
                "compile",
                "pyproject.toml",
                f"requirements/{source}",
                "--extra",
                "package",
                "--extra",
                "video",
                "--extra",
                "face",
                "--python-platform",
                platform,
                "--python-version",
                "3.11",
                "--generate-hashes",
                "--emit-index-url",
                "--no-header",
                "--no-annotate",
                "--torch-backend",
                backend,
                "--output-file",
                str(lock),
                "--quiet",
            ],
            cwd=ROOT,
            check=True,
            stdout=subprocess.DEVNULL,
        )
        content = lock.read_text()
        lock.write_text(
            f"# Generated by scripts/lock_backend_requirements.py; {resolver}.\n"
            f"--extra-index-url https://download.pytorch.org/whl/{backend}\n" + content
        )


if __name__ == "__main__":
    main()
