name: Linux Runner Maintenance

on:
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: [self-hosted, Linux, X64, localsr-linux-builder]
    steps:
      - name: Verify installed system libraries
        run: |
          sudo rm -f /usr/local/lib/libpsm2.so.2 /usr/local/lib/libucp.so.0 /usr/local/lib/libze_loader.so.1
          sudo ldconfig
          ldconfig -p | grep -E "libze_loader|librdmacm|libibverbs|libpsm2|libucp"
